// flow-typed signature: 1141fdb03df7348ed72066b9c53d9310
// flow-typed version: <<STUB>>/bookshelf_v0.10.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookshelf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookshelf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookshelf/bookshelf' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/events' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/model' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/promise' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/base/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/bookshelf' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/constants' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/errors' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/extend' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/helpers' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/model' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/BookshelfModel' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/bookshelfNext' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/configureRelations' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/eagerLoader' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/example/index' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/example/init-models' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/next/modelFactory' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/pagination' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/registry' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/virtuals' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/plugins/visibility' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/lib/sync' {
  declare module.exports: any;
}

declare module 'bookshelf/scripts/build' {
  declare module.exports: any;
}

declare module 'bookshelf/scripts/promise' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/events' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/model' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/promise' {
  declare module.exports: any;
}

declare module 'bookshelf/src/base/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/src/bookshelf' {
  declare module.exports: any;
}

declare module 'bookshelf/src/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/src/constants' {
  declare module.exports: any;
}

declare module 'bookshelf/src/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/src/errors' {
  declare module.exports: any;
}

declare module 'bookshelf/src/extend' {
  declare module.exports: any;
}

declare module 'bookshelf/src/helpers' {
  declare module.exports: any;
}

declare module 'bookshelf/src/model' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/pagination' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/registry' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/virtuals' {
  declare module.exports: any;
}

declare module 'bookshelf/src/plugins/visibility' {
  declare module.exports: any;
}

declare module 'bookshelf/src/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/src/sync' {
  declare module.exports: any;
}

declare module 'bookshelf/test/base/index' {
  declare module.exports: any;
}

declare module 'bookshelf/test/base/tests/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/test/base/tests/eager' {
  declare module.exports: any;
}

declare module 'bookshelf/test/base/tests/events' {
  declare module.exports: any;
}

declare module 'bookshelf/test/base/tests/model' {
  declare module.exports: any;
}

declare module 'bookshelf/test/base/tests/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/test/index' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/config' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/inserts' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/json/inserts' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/json/migration' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/json/objects' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/json/supported' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/migration' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/objects' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/helpers/plugin' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/json' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/model' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/output/Collection' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/output/Relations' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/plugin' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/plugins/pagination' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/plugins/registry' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/plugins/virtuals' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/plugins/visibility' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/relation' {
  declare module.exports: any;
}

declare module 'bookshelf/test/integration/relations' {
  declare module.exports: any;
}

declare module 'bookshelf/test/unit/collection' {
  declare module.exports: any;
}

declare module 'bookshelf/test/unit/model' {
  declare module.exports: any;
}

declare module 'bookshelf/test/unit/sql/model' {
  declare module.exports: any;
}

declare module 'bookshelf/test/unit/sql/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookshelf/bookshelf.js' {
  declare module.exports: $Exports<'bookshelf/bookshelf'>;
}
declare module 'bookshelf/lib/base/collection.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/collection'>;
}
declare module 'bookshelf/lib/base/eager.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/eager'>;
}
declare module 'bookshelf/lib/base/events.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/events'>;
}
declare module 'bookshelf/lib/base/model.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/model'>;
}
declare module 'bookshelf/lib/base/promise.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/promise'>;
}
declare module 'bookshelf/lib/base/relation.js' {
  declare module.exports: $Exports<'bookshelf/lib/base/relation'>;
}
declare module 'bookshelf/lib/bookshelf.js' {
  declare module.exports: $Exports<'bookshelf/lib/bookshelf'>;
}
declare module 'bookshelf/lib/collection.js' {
  declare module.exports: $Exports<'bookshelf/lib/collection'>;
}
declare module 'bookshelf/lib/constants.js' {
  declare module.exports: $Exports<'bookshelf/lib/constants'>;
}
declare module 'bookshelf/lib/eager.js' {
  declare module.exports: $Exports<'bookshelf/lib/eager'>;
}
declare module 'bookshelf/lib/errors.js' {
  declare module.exports: $Exports<'bookshelf/lib/errors'>;
}
declare module 'bookshelf/lib/extend.js' {
  declare module.exports: $Exports<'bookshelf/lib/extend'>;
}
declare module 'bookshelf/lib/helpers.js' {
  declare module.exports: $Exports<'bookshelf/lib/helpers'>;
}
declare module 'bookshelf/lib/model.js' {
  declare module.exports: $Exports<'bookshelf/lib/model'>;
}
declare module 'bookshelf/lib/next/BookshelfModel.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/BookshelfModel'>;
}
declare module 'bookshelf/lib/next/bookshelfNext.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/bookshelfNext'>;
}
declare module 'bookshelf/lib/next/configureRelations.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/configureRelations'>;
}
declare module 'bookshelf/lib/next/eagerLoader.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/eagerLoader'>;
}
declare module 'bookshelf/lib/next/example/index.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/example/index'>;
}
declare module 'bookshelf/lib/next/example/init-models.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/example/init-models'>;
}
declare module 'bookshelf/lib/next/modelFactory.js' {
  declare module.exports: $Exports<'bookshelf/lib/next/modelFactory'>;
}
declare module 'bookshelf/lib/plugins/pagination.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/pagination'>;
}
declare module 'bookshelf/lib/plugins/registry.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/registry'>;
}
declare module 'bookshelf/lib/plugins/virtuals.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/virtuals'>;
}
declare module 'bookshelf/lib/plugins/visibility.js' {
  declare module.exports: $Exports<'bookshelf/lib/plugins/visibility'>;
}
declare module 'bookshelf/lib/relation.js' {
  declare module.exports: $Exports<'bookshelf/lib/relation'>;
}
declare module 'bookshelf/lib/sync.js' {
  declare module.exports: $Exports<'bookshelf/lib/sync'>;
}
declare module 'bookshelf/scripts/build.js' {
  declare module.exports: $Exports<'bookshelf/scripts/build'>;
}
declare module 'bookshelf/scripts/promise.js' {
  declare module.exports: $Exports<'bookshelf/scripts/promise'>;
}
declare module 'bookshelf/src/base/collection.js' {
  declare module.exports: $Exports<'bookshelf/src/base/collection'>;
}
declare module 'bookshelf/src/base/eager.js' {
  declare module.exports: $Exports<'bookshelf/src/base/eager'>;
}
declare module 'bookshelf/src/base/events.js' {
  declare module.exports: $Exports<'bookshelf/src/base/events'>;
}
declare module 'bookshelf/src/base/model.js' {
  declare module.exports: $Exports<'bookshelf/src/base/model'>;
}
declare module 'bookshelf/src/base/promise.js' {
  declare module.exports: $Exports<'bookshelf/src/base/promise'>;
}
declare module 'bookshelf/src/base/relation.js' {
  declare module.exports: $Exports<'bookshelf/src/base/relation'>;
}
declare module 'bookshelf/src/bookshelf.js' {
  declare module.exports: $Exports<'bookshelf/src/bookshelf'>;
}
declare module 'bookshelf/src/collection.js' {
  declare module.exports: $Exports<'bookshelf/src/collection'>;
}
declare module 'bookshelf/src/constants.js' {
  declare module.exports: $Exports<'bookshelf/src/constants'>;
}
declare module 'bookshelf/src/eager.js' {
  declare module.exports: $Exports<'bookshelf/src/eager'>;
}
declare module 'bookshelf/src/errors.js' {
  declare module.exports: $Exports<'bookshelf/src/errors'>;
}
declare module 'bookshelf/src/extend.js' {
  declare module.exports: $Exports<'bookshelf/src/extend'>;
}
declare module 'bookshelf/src/helpers.js' {
  declare module.exports: $Exports<'bookshelf/src/helpers'>;
}
declare module 'bookshelf/src/model.js' {
  declare module.exports: $Exports<'bookshelf/src/model'>;
}
declare module 'bookshelf/src/plugins/pagination.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/pagination'>;
}
declare module 'bookshelf/src/plugins/registry.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/registry'>;
}
declare module 'bookshelf/src/plugins/virtuals.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/virtuals'>;
}
declare module 'bookshelf/src/plugins/visibility.js' {
  declare module.exports: $Exports<'bookshelf/src/plugins/visibility'>;
}
declare module 'bookshelf/src/relation.js' {
  declare module.exports: $Exports<'bookshelf/src/relation'>;
}
declare module 'bookshelf/src/sync.js' {
  declare module.exports: $Exports<'bookshelf/src/sync'>;
}
declare module 'bookshelf/test/base/index.js' {
  declare module.exports: $Exports<'bookshelf/test/base/index'>;
}
declare module 'bookshelf/test/base/tests/collection.js' {
  declare module.exports: $Exports<'bookshelf/test/base/tests/collection'>;
}
declare module 'bookshelf/test/base/tests/eager.js' {
  declare module.exports: $Exports<'bookshelf/test/base/tests/eager'>;
}
declare module 'bookshelf/test/base/tests/events.js' {
  declare module.exports: $Exports<'bookshelf/test/base/tests/events'>;
}
declare module 'bookshelf/test/base/tests/model.js' {
  declare module.exports: $Exports<'bookshelf/test/base/tests/model'>;
}
declare module 'bookshelf/test/base/tests/relation.js' {
  declare module.exports: $Exports<'bookshelf/test/base/tests/relation'>;
}
declare module 'bookshelf/test/index.js' {
  declare module.exports: $Exports<'bookshelf/test/index'>;
}
declare module 'bookshelf/test/integration.js' {
  declare module.exports: $Exports<'bookshelf/test/integration'>;
}
declare module 'bookshelf/test/integration/collection.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/collection'>;
}
declare module 'bookshelf/test/integration/helpers/config.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/config'>;
}
declare module 'bookshelf/test/integration/helpers/inserts.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/inserts'>;
}
declare module 'bookshelf/test/integration/helpers/json/inserts.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/json/inserts'>;
}
declare module 'bookshelf/test/integration/helpers/json/migration.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/json/migration'>;
}
declare module 'bookshelf/test/integration/helpers/json/objects.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/json/objects'>;
}
declare module 'bookshelf/test/integration/helpers/json/supported.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/json/supported'>;
}
declare module 'bookshelf/test/integration/helpers/migration.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/migration'>;
}
declare module 'bookshelf/test/integration/helpers/objects.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/objects'>;
}
declare module 'bookshelf/test/integration/helpers/plugin.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/helpers/plugin'>;
}
declare module 'bookshelf/test/integration/json.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/json'>;
}
declare module 'bookshelf/test/integration/model.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/model'>;
}
declare module 'bookshelf/test/integration/output/Collection.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/output/Collection'>;
}
declare module 'bookshelf/test/integration/output/Relations.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/output/Relations'>;
}
declare module 'bookshelf/test/integration/plugin.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/plugin'>;
}
declare module 'bookshelf/test/integration/plugins/pagination.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/plugins/pagination'>;
}
declare module 'bookshelf/test/integration/plugins/registry.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/plugins/registry'>;
}
declare module 'bookshelf/test/integration/plugins/virtuals.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/plugins/virtuals'>;
}
declare module 'bookshelf/test/integration/plugins/visibility.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/plugins/visibility'>;
}
declare module 'bookshelf/test/integration/relation.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/relation'>;
}
declare module 'bookshelf/test/integration/relations.js' {
  declare module.exports: $Exports<'bookshelf/test/integration/relations'>;
}
declare module 'bookshelf/test/unit/collection.js' {
  declare module.exports: $Exports<'bookshelf/test/unit/collection'>;
}
declare module 'bookshelf/test/unit/model.js' {
  declare module.exports: $Exports<'bookshelf/test/unit/model'>;
}
declare module 'bookshelf/test/unit/sql/model.js' {
  declare module.exports: $Exports<'bookshelf/test/unit/sql/model'>;
}
declare module 'bookshelf/test/unit/sql/sync.js' {
  declare module.exports: $Exports<'bookshelf/test/unit/sql/sync'>;
}
