// flow-typed signature: c80d22bc8a39ffed715f718fd715e527
// flow-typed version: <<STUB>>/bookshelf-camelcase_v1.1.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookshelf-camelcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookshelf-camelcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookshelf-camelcase/camelcase' {
  declare module.exports: any;
}

declare module 'bookshelf-camelcase/camelcase.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookshelf-camelcase/camelcase.js' {
  declare module.exports: $Exports<'bookshelf-camelcase/camelcase'>;
}
declare module 'bookshelf-camelcase/camelcase.spec.js' {
  declare module.exports: $Exports<'bookshelf-camelcase/camelcase.spec'>;
}
