// flow-typed signature: d18e4532ea55e1c3d15bfe4b0973b8b5
// flow-typed version: <<STUB>>/errorhandler_v1.5.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'errorhandler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'errorhandler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'errorhandler/index' {
  declare module.exports: $Exports<'errorhandler'>;
}
declare module 'errorhandler/index.js' {
  declare module.exports: $Exports<'errorhandler'>;
}
