// flow-typed signature: 9aab4b850289edbccc41b81620b3a820
// flow-typed version: <<STUB>>/react-loader_v2.4.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loader/lib/react-loader' {
  declare module.exports: any;
}

declare module 'react-loader/lib/react-loader' {
  declare module.exports: any;
}

declare module 'react-loader/test/spec/react-loader-test' {
  declare module.exports: any;
}

declare module 'react-loader/test/spec/suite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loader/lib/react-loader.js' {
  declare module.exports: $Exports<'react-loader/lib/react-loader'>;
}
declare module 'react-loader/lib/react-loader.jsx' {
  declare module.exports: $Exports<'react-loader/lib/react-loader'>;
}
declare module 'react-loader/test/spec/react-loader-test.js' {
  declare module.exports: $Exports<'react-loader/test/spec/react-loader-test'>;
}
declare module 'react-loader/test/spec/suite.js' {
  declare module.exports: $Exports<'react-loader/test/spec/suite'>;
}
