// flow-typed signature: 78f621b134cdcc5149f33cb26ca9dff5
// flow-typed version: <<STUB>>/@insidersbyte/react-markdown-editor_v0.3.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@insidersbyte/react-markdown-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@insidersbyte/react-markdown-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@insidersbyte/react-markdown-editor/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@insidersbyte/react-markdown-editor/dist/index.js' {
  declare module.exports: $Exports<'@insidersbyte/react-markdown-editor/dist/index'>;
}
